services:
  nginx:
    build:
      context: .
    container_name: ${APP_NAME}
    expose: 
      - 80/tcp
      - ${EXTERNAL_SSH_PORT}/tcp
    ports:
      - ${EXTERNAL_HTTP_PORT}:80
      - ${EXTERNAL_SSH_PORT}:22
    environment:
      SSH_AUTHORIZED_KEY: ${SSH_AUTHORIZED_KEY}
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      # HTTP роутер
      - "traefik.http.routers.${APP_NAME}-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-web.entrypoints=${TRAEFIK_ENTRYPOINT_WEB:-web}"
      - "traefik.http.routers.${APP_NAME}-web.service=${APP_NAME}-service"
      # HTTPS роутер
      - "traefik.http.routers.${APP_NAME}-websecure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-websecure.entrypoints=${TRAEFIK_ENTRYPOINT_WEBSECURE:-websecure}"
      - "traefik.http.routers.${APP_NAME}-websecure.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.routers.${APP_NAME}-websecure.service=${APP_NAME}-service"
      # Один сервис для обоих роутеров
      - "traefik.http.services.${APP_NAME}-service.loadbalancer.server.port=80"



networks:
  default:
    name: traefik-default
    external: true
